### PR TITLE
Fix domchildnode.replacewith parsing errors

### PR DESCRIPTION
**Pull request by haszi**
Add errors section to DOMChildNode's replaceWith method to fix parsing errors.

### CODE REVIEW

**Review by Girgias — APPROVED** [review]

**Comment by Girgias** [comment]
Thank you!

**Comment by haszi** [comment]
@Girgias There is something weird going on with the translations' parsing/validation where locally they fail or at least raise a warning but they pass with each PR on GitHub. I've seen this in both translations I've looked at today: `doc-fr` (because of what this PR fixed) and `doc-de` (a new entity was used but not added to their entity list).

I have no idea where to start looking for the root cause but I thought I'd let you know.

**Comment by Girgias** [comment]
> @Girgias There is something weird going on with the translations' parsing/validation where locally they fail or at least raise a warning but they pass with each PR on GitHub. I've seen this in both translations I've looked at today: `doc-fr` (because of what this PR fixed) and `doc-de` (a new entity was used but not added to their entity list).
> 
> I have no idea where to start looking for the root cause but I thought I'd let you know.

What do you mean that the translation fails? I don't have any issues localy.

Is this a PhD specific issue?

**Comment by Girgias** [comment]
Oh, one thing, is your `doc-base` repo up to date?

**Comment by haszi** [comment]
Yes, `doc-base` is up to date but `doc-de` still fails validation (with `doc-base/configure.php`) on Windows (PHP 8.2.4 with libxml 2.10.3) but passes on Debian (PHP 8.2.7 with libxml 2.9.14).

The reason for the failure is that they have added `&install.cloud.digitalocean;` to one of their files (following the English manual) but forgot to add the entity itself. Hence this error from `php doc-base/configure.php --with-lang=doc-de`:
```
 &install.cloud.digitalocean;
------------------------------^
 Entity 'install.cloud.digitalocean' not defined
```

I think this is a valid failure but then why doesn't it fail on Debian? I don't know. :-)

`doc-fr`'s warning did show up on both Windows and Debian but a failed XInclude evaluation is not an error that would fail the build. And noone will open the logs to check for warnings. :-) I just checked some logs of PRs before this one was merged and sure enough, the warnings are there.

```
XPointer evaluation failed: #xmlns(db=http://docbook.org/ns/docbook) xpointer(id('domchildnode.replacewith')/db:refsect1[@role='errors'])

could not load /home/runner/work/doc-fr/doc-fr/doc-base/manual.xml, and no fallback was found

XPointer evaluation failed: #xmlns(db=http://docbook.org/ns/docbook) xpointer(id('domchildnode.replacewith')/db:refsect1[@role='errors'])

could not load /home/runner/work/doc-fr/doc-fr/doc-base/manual.xml, and no fallback was found
```

**Comment by Girgias** [comment]
Oh, one thing, is your `doc-base` repo up to date?

> Yes, `doc-base` is up to date but `doc-de` still fails validation (with `doc-base/configure.php`) on Windows (PHP 8.2.4 with libxml 2.10.3) but passes on Debian (PHP 8.2.7 with libxml 2.9.14).
> 
> The reason for the failure is that they have added `&install.cloud.digitalocean;` to one of their files (following the English manual) but forgot to add the entity itself. Hence this error from `php doc-base/configure.php --with-lang=doc-de`:
> 
> ```
>  &install.cloud.digitalocean;
> ------------------------------^
>  Entity 'install.cloud.digitalocean' not defined
> ```
> 
> I think this is a valid failure but then why doesn't it fail on Debian? I don't know. :-)
> 
> `doc-fr`'s warning did show up on both Windows and Debian but a failed XInclude evaluation is not an error that would fail the build. And noone will open the logs to check for warnings. :-) I just checked some logs of PRs before this one was merged and sure enough, the warnings are there.
> 
> ```
> XPointer evaluation failed: #xmlns(db=http://docbook.org/ns/docbook) xpointer(id('domchildnode.replacewith')/db:refsect1[@role='errors'])
> 
> could not load /home/runner/work/doc-fr/doc-fr/doc-base/manual.xml, and no fallback was found
> 
> XPointer evaluation failed: #xmlns(db=http://docbook.org/ns/docbook) xpointer(id('domchildnode.replacewith')/db:refsect1[@role='errors'])
> 
> could not load /home/runner/work/doc-fr/doc-fr/doc-base/manual.xml, and no fallback was found
> ```

The `&install.cloud.digitalocean;` entity should be generated by configure, maybe there is some path translation issue on Windows which is why it doesn't fail on Linux.

About the XIncludes, IIRC the reason we didn't make them error the builds is because it would potentially break translations that are in state that is outdated but "valid" but new English files that try to XInclude from those outdated files would needlessly break the build for those translations.

This is what I initially thought the doc-fr cause was. But it might make sense to reevaluate this (well I know doc-es currently has XInclude failures because I haven't finished syncing up reference/spl folder yet) or have it as a flag to configure that could be enabled in CI for doc-en and translations (or disabled and only have the problematic translations have it)

**Comment by haszi** [comment]
> The `&install.cloud.digitalocean;` entity should be generated by configure, maybe there is some path translation issue on Windows which is why it doesn't fail on Linux.

That makes sense. I'll just ignore Windows failures if the same thing is passing on Linux in the future. :-)


> About the XIncludes, IIRC the reason we didn't make them error the builds is because it would potentially break translations that are in state that is outdated but "valid" but new English files that try to XInclude from those outdated files would needlessly break the build for those translations.

That makes sense too. 

> This is what I initially thought the doc-fr cause was. But it might make sense to reevaluate this (well I know doc-es currently has XInclude failures because I haven't finished syncing up reference/spl folder yet) or have it as a flag to configure that could be enabled in CI for doc-en and translations (or disabled and only have the problematic translations have it)

Adding a flag might be the easiest way. And at least `doc-en` should fail on any kind of validation error since every translation is depends on it.

**Comment by Girgias** [comment]
Yeah `doc-en` should fail if there are XInclude issues

**Pull request merged**
