### PR TITLE
Fix constant: this is not PDO here

### PR DESCRIPTION
**Pull request by bohwaz**

### CODE REVIEW

**Comment by Girgias** [comment]
This change needs to be done upstream (to doc-en)

**Comment by bohwaz** [comment]
@Girgias please don't close, the error is ONLY in the french version, not in upstream.

See https://github.com/php/doc-en/blob/master/reference/sqlite3/sqlite3/createfunction.xml#L86

**Comment by Girgias** [comment]
This does not refer to the same file. The english upstream file is this one: https://github.com/php/doc-en/blob/master/reference/pdo_sqlite/PDO/sqliteCreateFunction.xml and the corresponding online doc page is https://www.php.net/manual/en/pdo.sqlitecreatefunction.php

**Comment by bohwaz** [comment]
> This does not refer to the same file. The english upstream file is this one: https://github.com/php/doc-en/blob/master/reference/pdo_sqlite/PDO/sqliteCreateFunction.xml and the corresponding online doc page is https://www.php.net/manual/en/pdo.sqlitecreatefunction.php

Oooh I see my bad, I edited the wrong file. I made a new PR #48 then.

**Pull request closed without merging**
