### PR TITLE
Update install unix apache2

### PR DESCRIPTION
**Pull request by happytodev**
Update FR translation to the EN Hashtag a89c6d71c7b65e3de84f26230fbf72c9b8948adf

### CODE REVIEW

**Comment by devnexen** [comment]
seems you created this PR on top of your previous PR's branch ?

**Comment by happytodev** [comment]
> seems you created this PR on top of your previous PR's branch ?

Oh no. I'm sorry, it's a mistake. I think I need some more training on git :-(

How can I fix this?

**Comment by devnexen** [comment]
That s

> > seems you created this PR on top of your previous PR's branch ?
> 
> Oh no. I'm sorry, it's a mistake. I think I need some more training on git :-(

That is fine, no worries :)
> 
> How can I fix this?

You can simply recreate a new PR, especially your apache change is fairly small.

**Comment by happytodev** [comment]
> That s
> 
> > > seems you created this PR on top of your previous PR's branch ?
> > 
> > 
> > Oh no. I'm sorry, it's a mistake. I think I need some more training on git :-(
> 
> That is fine, no worries :)
> 
> > How can I fix this?
> 
> You can simply recreate a new PR, especially your apache change is fairly small.

I probably did something really wrong because when I create a new pull request, I have the others commit into : 

image

As you can see, I'm not really an expert of git. What do you suggest to fix this mess ?

**Comment by devnexen** [comment]
oh I see in your previous PR you did not create a branch but directly used master.

**Comment by devnexen** [comment]
> 
> As you can see, I'm not really an expert of git. What do you suggest to fix this mess ?

It is recommended to create a bew branch from the target's one (here master).

**Comment by happytodev** [comment]
> oh I see in your previous PR you did not create a branch but directly used master.

oh yes, that's true, sadly :-(.
What can I do now ?

(Sorry)

**Comment by happytodev** [comment]
> > As you can see, I'm not really an expert of git. What do you suggest to fix this mess ?
> 
> It is recommended to create a new branch from the target's one (here master).

Could you be more precise please ? I don't want to make a bigger mess than this :-(

**Comment by devnexen** [comment]
> > > As you can see, I'm not really an expert of git. What do you suggest to fix this mess ?
> > 
> > 
> > It is recommended to create a new branch from the target's one (here master).
> 
> Could you be more precise please ? I don't want to make a bigger mess than this :-(

It might be possible to recreate your two PR from scratch, keeping your diffs somewhere to be reapplied, your local master change needs to be in [sync with the upstream master's](https://github.com/php/doc-fr/commit/61054493d28854c3496d0bd88a79c47fcc06eb9b), for example this [set of actions can be applied](https://www.ocpsoft.org/tutorials/git/reset-and-sync-local-respository-with-remote-branch/).

**Comment by happytodev** [comment]
> > > > As you can see, I'm not really an expert of git. What do you suggest to fix this mess ?
> > > 
> > > 
> > > It is recommended to create a new branch from the target's one (here master).
> > 
> > 
> > Could you be more precise please ? I don't want to make a bigger mess than this :-(
> 
> It might be possible to recreate your two PR from scratch, keeping your diffs somewhere to be reapplied, your local master change needs to be in [sync with the upstream master's](https://github.com/php/doc-fr/commit/61054493d28854c3496d0bd88a79c47fcc06eb9b), for example this [set of actions can be applied](https://www.ocpsoft.org/tutorials/git/reset-and-sync-local-respository-with-remote-branch/).

Thank you for your help, I will try tomorrow.

**Pull request closed without merging**
