### PR TITLE
Update book.xml

### PR DESCRIPTION
**Pull request by JackPotte**
English translation instead of blank

### CODE REVIEW

**Comment by afilina** [comment]
@Girgias I'm at a loss as to why the pipeline is failing. I don't see how it's related to the change. I tried to rerun it in case it was a flaky test, but it fails in the same place.

**Comment by Girgias** [comment]
> @Girgias I'm at a loss as to why the pipeline is failing. I don't see how it's related to the change. I tried to rerun it in case it was a flaky test, but it fails in the same place.

It was just because the build was broken as a whole after the fbsql doc removal.

However this is missing an update to the EN-Revision tag at the top of the file to: ``e7853a8a24fd5de419860cf00e00320905e7cb4c``

**Comment by afilina** [comment]
@JackPotte http://doc.php.net/tutorial/translating.php

> Every file in Git has a commit hash. It is basically the current version of the specified file. We use commit hashes to check if a file is synchronized with its English counterpart: to find out if the translation is up-to-date. That's why every file in your translation requires an EN-Revision comment with the following syntax:
>
> &lt;!-- EN-Revision: [some commit hash] Maintainer: [username] Status: ready --&gt;

**Comment by Girgias** [comment]
Thanks!

**Pull request merged**
