### PR TITLE
curl: sync CURL_SSLVERSION_TLSv1_3 constant.

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by Girgias** [comment]
Syncing the complete file doesn't look to hard rn: http://doc.php.net/revcheck.php?p=plain&lang=fr&hbp=81905a86337b291fb449fdf24a350b7ef0607759&f=reference/curl/constants.xml&c=on would you do it?

**Comment by devnexen** [comment]
sure thing :-)

**Review by adoy — CHANGES_REQUESTED** [review]
`reference/curl/constants.xml` looks got but you forgot to update the Revision tracking tag.

It would also be nice to do the same with `reference/curl/functions/curl-setopt.xml`.
http://doc.php.net/revcheck.php?p=plain&lang=fr&hbp=5af60875f7e8da6c61d2f649a4f4d2626561dd9c&f=reference/curl/functions/curl-setopt.xml&c=on

Updating just a subset of the page make it hard to sync the translation :)

Thanks

**Comment by devnexen** [comment]
ah I m bad at remembering those details, thanks , will do.

**Comment by adoy** [comment]
> ah I m bad at remembering those details, thanks , will do.

If you look at the link I gave you there are few more things to translate to be in sync with `52dbbb3856a16174bfd0a96e6df8c52f236397eb` :-)

**Comment by adoy** [comment]
I took the liberty to push the missing diffs on your PR.

**Review by adoy — APPROVED** [review]

**Pull request merged**
